authors:
  pbk:
    name: Praveen Kulkarni
    description: AI/ML/HPC/AR/VR/IoT
    avatar: https://avatars.githubusercontent.com/pbk0
  nsavi:
    name: Savitha Nagaraju
    description: ...
    avatar: https://avatars.githubusercontent.com/SavithaNagaraju